[tool.black]
line-length = 88

[tool.isort]
profile = "black"
known_first_party = "src"
combine_as_imports = true

[tool.pytest.ini_options]
python_files = "tests.py test_*.py"
addopts = "--cov --no-cov-on-fail"
timeout = 30
pythonpath = "src"
testpaths = ["src"]
asyncio_mode = "auto"

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
skip_covered = true
show_missing = true
fail_under = 100

[tool.mypy]
python_version = "3.10"
pretty = true
files = "src"

show_error_codes = true
no_implicit_reexport = true
no_implicit_optional = true
strict_equality = true
strict_optional = true
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
ignore_missing_imports = false

warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true
