# syntax=docker/dockerfile:labs
FROM python:3.10-slim-bullseye

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

ENV PATH="/app/venv/bin/:$PATH"

RUN useradd --user-group --create-home --home-dir /app app

WORKDIR /app

RUN python -m venv venv

